variables:
  GITHUB_USERNAME: "Pinont"
  GITHUB_REPO: "SingularityLib"
  GITHUB_URL: "https://github.com/$GITHUB_USERNAME/$GITHUB_REPO.git"

stages:
  - sync

sync_to_github:
  stage: sync
  script:
    - git config --global user.email "pinozen.thailand@gmail.com"
    - git config --global user.name $GITHUB_USERNAME
    - git remote add github $GITHUB_URL
    - git fetch --all
    - git push --all https://$GITHUB_TOKEN@github.com/$GITHUB_USERNAME/$GITHUB_REPO.git
    - git push --tags https://$GITHUB_TOKEN@github.com/$GITHUB_USERNAME/$GITHUB_REPO.git
  only:
    - branches