package com.github.pinont.singularitylib.processor;

import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.Filer;
import javax.annotation.processing.Messager;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.annotation.processing.SupportedSourceVersion;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import javax.tools.Diagnostic;
import javax.tools.FileObject;
import javax.tools.StandardLocation;
import java.io.IOException;
import java.io.Writer;
import java.util.Set;
import java.util.TreeSet;

/**
 * Compile-time annotation processor that replaces the runtime Reflections classpath
 * scan of {@code @AutoRegister} classes with a static index.
 * <p>
 * For every compilation round it accumulates the fully-qualified names of all
 * concrete classes annotated with
 * {@code com.github.pinont.singularitylib.api.annotation.AutoRegister} and, once
 * processing is over, writes them into the generated resources as
 * {@value #INDEX_RESOURCE} (one fully-qualified class name per line). That resource
 * is copied into the compiled jar, where {@code Register} picks it up at plugin
 * startup — no runtime classpath scanning required.
 * <p>
 * The processor deliberately has <b>zero dependencies</b>: it never loads the
 * annotation class directly, only its fully-qualified name. This keeps the
 * processor jar usable as a bare {@code annotationProcessorPaths} entry without
 * dragging the whole library into consumer builds.
 */
@SupportedAnnotationTypes("com.github.pinont.singularitylib.api.annotation.AutoRegister")
@SupportedSourceVersion(SourceVersion.RELEASE_25)
public final class AutoRegisterProcessor extends AbstractProcessor {

    /**
     * Generated-resources path of the auto-register index. This is the single
     * constant read by {@code Register} at runtime.
     */
    public static final String INDEX_RESOURCE = "META-INF/singularitylib/auto-register-index.properties";

    /**
     * Fully-qualified name of {@code @AutoRegister}. Referenced by name on purpose:
     * the processor jar must never compile against the library it indexes.
     */
    private static final String AUTO_REGISTER_ANNOTATION =
            "com.github.pinont.singularitylib.api.annotation.AutoRegister";

    /** Collected class names, sorted for deterministic output. */
    private final Set<String> classNames = new TreeSet<>();
    private boolean written = false;

    /**
     * Default constructor for the processor (required by the service mechanism).
     */
    public AutoRegisterProcessor() {
    }

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        if (roundEnv.processingOver()) {
            writeIndex();
            return false;
        }

        TypeElement annotation =
                processingEnv.getElementUtils().getTypeElement(AUTO_REGISTER_ANNOTATION);
        if (annotation == null) {
            // @AutoRegister is not on this compilation's classpath: nothing to index.
            return false;
        }

        for (Element element : roundEnv.getElementsAnnotatedWith(annotation)) {
            if (element.getKind() != ElementKind.CLASS) {
                continue;
            }
            TypeElement type = (TypeElement) element;
            // Register instantiates via the no-arg constructor; abstract types can
            // never be registered, so keep them out of the index.
            if (type.getModifiers().contains(Modifier.ABSTRACT)) {
                continue;
            }
            classNames.add(type.getQualifiedName().toString());
        }
        return false;
    }

    /**
     * Writes {@value #INDEX_RESOURCE} into the generated resources once all rounds
     * are done and at least one class was found. If no {@code @AutoRegister} class
     * exists in the compilation, no index is produced.
     */
    private void writeIndex() {
        if (written || classNames.isEmpty()) {
            return;
        }
        written = true;

        Messager messager = processingEnv.getMessager();
        Filer filer = processingEnv.getFiler();
        try {
            FileObject resource =
                    filer.createResource(StandardLocation.CLASS_OUTPUT, "", INDEX_RESOURCE);
            try (Writer writer = resource.openWriter()) {
                writer.write("# Generated by SingularityLib AutoRegisterProcessor - do not edit\n");
                writer.write("# One fully-qualified class name per line.\n");
                for (String className : classNames) {
                    writer.write(className);
                    writer.write('\n');
                }
            }
        } catch (IOException e) {
            messager.printMessage(Diagnostic.Kind.ERROR,
                    "Failed to write auto-register index " + INDEX_RESOURCE + ": " + e.getMessage());
        }
    }
}