name: SingularityLib Build and Publish
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Verify tag matches POM version
        run: |
          TAG_VERSION="${GITHUB_REF_NAME#v}"
            POM_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:3.1.0:exec)
          if [ "$TAG_VERSION" != "$POM_VERSION" ]; then
            echo "Tag version v$TAG_VERSION does not match POM version $POM_VERSION"
            exit 1
          fi

      - name: Build
        run: mvn -B -U clean package

      - name: Deploy
        run: mvn -B deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}