name: Publish SNAPSHOT (Minimal)

on:
  push:
    branches: [ main ]

jobs:
  snapshot:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show ref + actor (debug)
        run: |
          echo "Actor: $GITHUB_ACTOR"
          echo "Ref:   $GITHUB_REF"

      - name: Extract version
        id: v
        run: |
          VERSION=$(grep -m1 '<version>' pom.xml | sed -E 's/.*<version>([^<]+)<\/version>.*/\1/')
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          if [[ "$VERSION" == *-SNAPSHOT ]]; then
            echo "deploy=true" >> "$GITHUB_OUTPUT"
          else
            echo "deploy=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Abort (not a SNAPSHOT)
        if: steps.v.outputs.deploy != 'true'
        run: echo "Version ${{ steps.v.outputs.version }} is not a SNAPSHOT, skipping."

      - name: Set up Java + credentials
        if: steps.v.outputs.deploy == 'true'
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '23'
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Print generated settings.xml (masked)
        if: steps.v.outputs.deploy == 'true'
        run: |
          echo "---- settings.xml ----"
          sed 's/<password>.*<\/password>/<password>***<\/password>/' ~/.m2/settings.xml || true
          echo "----------------------"

      - name: Deploy
        if: steps.v.outputs.deploy == 'true'
        run: mvn -B -e -DskipTests deploy

      - name: Summary
        run: |
          echo "Version: ${{ steps.v.outputs.version }}"
          echo "Deploy:  ${{ steps.v.outputs.deploy }}"