name: Snapshot Deploy (Central + GitHub)

on:
  push:
    branches: [ main ]

jobs:
  snapshot:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Determine version
        id: ver
        run: |
          VERSION=$(grep -m1 '<version>' pom.xml | sed -E 's/.*<version>([^<]+)<\/version>.*/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          if [[ "$VERSION" == *-SNAPSHOT ]]; then
            echo "deploy=true" >> $GITHUB_OUTPUT
          else
            echo "deploy=false" >> $GITHUB_OUTPUT
          fi

      - name: Abort (not a snapshot)
        if: steps.ver.outputs.deploy != 'true'
        run: echo "Version ${{ steps.ver.outputs.version }} is not a SNAPSHOT, skipping."

      - name: Setup Java
        if: steps.ver.outputs.deploy == 'true'
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '23'

      - name: Import GPG key
        if: steps.ver.outputs.deploy == 'true'
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          gpg --list-secret-keys

      - name: Write settings.xml (both servers)
        if: steps.ver.outputs.deploy == 'true'
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<'EOF'
          <settings>
            <servers>
              <server>
                <id>sonatype</id>
                <username>${env.SONATYPE_USERNAME}</username>
                <password>${env.SONATYPE_PASSWORD}</password>
              </server>
              <server>
                <id>github</id>
                <username>${env.GITHUB_ACTOR}</username>
                <password>${env.GITHUB_TOKEN}</password>
              </server>
            </servers>
          </settings>
          EOF
          sed 's/<password>.*<\/password>/<password>***<\/password>/' ~/.m2/settings.xml

      - name: Deploy SNAPSHOT to Central
        if: steps.ver.outputs.deploy == 'true'
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          mvn -B -DskipTests -Dgpg.passphrase="${GPG_PASSPHRASE}" deploy

      - name: Deploy SNAPSHOT to GitHub Packages
        if: steps.ver.outputs.deploy == 'true'
        run: |
          mvn -B -DskipTests -Pgithub -Dgpg.skip=true deploy

      - name: Summary
        run: |
          echo "Version: ${{ steps.ver.outputs.version }}"
          echo "Central + GitHub deploy attempted (snapshot)."