name: Release Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Derive version from tag
        id: v
        run: |
          TAG="${GITHUB_REF_NAME}"      # e.g. v2.2.0
          VERSION="${TAG#v}"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Set up Temurin JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '23'
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Set release version (remove -SNAPSHOT)
        run: |
          mvn -B versions:set -DnewVersion="${{ steps.v.outputs.version }}" -DgenerateBackupPoms=false
          grep -m1 '<version>' pom.xml

      - name: Deploy Release
        run: mvn -B -DskipTests deploy

      - name: Package artifacts
        run: |
          cp target/*.jar ./artifact.jar
          ls -l

      - name: Create or Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "SingularityLib ${{ steps.v.outputs.version }}"
          generate_release_notes: true
          files: |
            artifact.jar
            target/*-sources.jar
            target/*-javadoc.jar

      - name: Post summary
        run: echo "Published version ${{ steps.v.outputs.version }}"